### ISSUE TITLE
Error 23 :) does not have a value Line 1 -> 0

### ISSUE THREAD

**Issue by slaviT** [Silly-V/Adobe-Illustrator#10] opened 2017-11-08 11:59 UTC
Error 23 :) does not have a value Line 1 -> 0

![image](https://user-images.githubusercontent.com/11461538/32548018-daa4cf3a-c48c-11e7-984b-29e55e0884ac.png)
 I got this error massage when I tried to call the script. It happened after I saved a defaut settings set.

How can I run it again.

**Comment by Silly-V** [comment] 2017-11-08 12:42
Hmm can you send me the settings file that got created ?

**Comment by slaviT** [comment] 2017-11-08 13:48
I can not remember the location of the file. Indeed there was some info while saving the preset settings but I just clicked as fast as possible on the ok button. Maybe if you tell me the default  path I could check it

**Comment by slaviT** [comment] 2017-11-08 14:02
OK I have different mac and was able to perform the settings saving. I located the json file and after deleted it everything worked perfect :)
I was in my home folder -> documents

**Comment by Silly-V** [comment] 2017-11-08 14:48
Okay, and what version of Illustrator are you running?

**Comment by Silly-V** [comment] 2017-11-08 14:49
I'd be interested in seeing if you can re produce this error: it may be caused by certain characters interrupting the settings reading. Can you attach the same settings file which is saved with the same kind of settings you used when you got the initial error?

**Comment by slaviT** [comment] 2017-11-08 14:55
19.02.0

**Comment by slaviT** [comment] 2017-11-08 20:29
Sure :)
I even made a short screen video of reproducing this error. Here take a look.
https://youtu.be/kov71G7XOFk

 After I got this error I looked into my the json file i in was empty. Here

<img width="919" alt="screen shot 2017-11-08 at 22 28 45" src="https://user-images.githubusercontent.com/11461538/32572732-35813802-c4d4-11e7-8fdf-da5ca3c75d57.png">

**Comment by slaviT** [comment] 2017-11-10 12:42
Hi my friend. I’ve left a detailed comment on GitHub. Even with short video of reproducing the error.

**Comment by Silly-V** [comment] 2017-11-10 14:37
Thank you for doing this! It is a surprise, that the JSON file is empty. I am hoping to fix this issue for you and anyone else. Does this happen on both of your macs the same way?

**Comment by slaviT** [comment] 2017-11-10 19:02
Hi,

I’m not sure if it happens on all of them. I have 4 MacBook Pros. Unfortunately I’m out of the office and I will be there on Tuesday. Then I can test the script for you.

But hey it’s still a great great script:))
It helped a lot ;)

BR
Slavi

**Comment by Silly-V** [comment] 2017-11-10 19:04
Thanks, now you can have your name immortalized in the very prestigious list of credits at the top of the script for people who help hunt down bugs!

**Comment by Silly-V** [comment] 2019-12-18 05:55
Well, unfortunately I do not think this one ended up being reproducible and could have been a temporary bug affected by some temporal conditions of the time. Closing now, will re-open if this bug re-surfaces again for anyone else.

**Closed by Silly-V** 2019-12-18 05:55 UTC

**Comment by ranamak** [comment] 2020-06-11 11:13
Hi, I am also getting this error,
Can anyone help me with this on how to resolve this error?
