### ISSUE TITLE
variableimporter crashing Illustrator 2021

### ISSUE THREAD

**Issue by tbelim** [Silly-V/Adobe-Illustrator#41] opened 2020-11-02 15:30 UTC
Trying to use the imported script and can't get past the changing option for the dataset name, Ai crashes as soon as I click any other tab or run the script.

**Comment by Silly-V** [comment] 2020-11-02 16:03
What is your Operating System?

**Comment by tbelim** [comment] 2020-11-02 17:18
MacOS 10.15.7 (19H2)

**Comment by Silly-V** [comment] 2020-11-02 19:34
Something is happening with your Catalina mac. I'll see if I can run some tests on a friend's Catalina system.

**Comment by i5man** [comment] 2020-11-03 03:42
I also experience the same issue, my operating system is MacOS 10.15.7. Before i update to illustrator 2021 the script seems work properly with no crash. Since then it always crash when i try to import variables after setting the dataset names.

**Comment by Silly-V** [comment] 2020-11-03 11:05
Ouch, my Catalina people, I feel your pain. I am looking into it.
If some of you can try this test, or see if it could be a work-around (besides keeping an old version of Ai for variable-importing) - try to have no documents open and run the script to create an XML file. If your case is that the document already has bound variables, and the XML file gets created successfully, you should be able to use the import button to import this XML file. And if the script worked then you'd have your custom dataset names. And if your artwork was already bound to previously-imported variables this artwork's variables should become automatically replaced with the XML file's variables of the same name.

**Comment by tbelim** [comment] 2020-11-03 15:05
Thank you so much for looking into this!! I was able to create an XML file. But I'm not sure what Import Button you are referring to.

**Comment by Silly-V** [comment] 2020-11-03 15:53
The import button inside the native variables panel. It is limited in comparison to the full VI script features - but mainly in that there's no way to make datasets out of your values as the VI script does. However, when using the XML with the VI script and then importing it natively will keep your datasets in there. If you have a situation where your variables are already bound, this XML file import is all you'll need to do and you don't have to worry about the binding.
However we do want to get you back up and working naturally asap. I've tested the script on my friend's Catalina mac but not sure if I didn't experience an error because his wasn't updated to the latest update.

**Comment by i5man** [comment] 2020-11-03 15:54
Thank you so much for your reply but in my case it's still crashing, 
i close all the document and try to do the cycle again but won't work. I choose the data file and the click on the options menu to assign my dataset name, test the dataset names (it work properly), i click on import variables, and then it crash. Sometimes it crash before i click on import variables, sometimes it seems work the cycle up dataset name pops up but then the adobe illustration quit when i hit the button.

**Comment by i5man** [comment] 2020-11-03 16:03
I just find where the xml file should be when it exported, although the Ai crash when the script is try to import variables but the XML file is successfully created. I try to import to Ai and it work!!!

Thank you so much for this :)

**Comment by tbelim** [comment] 2020-11-03 18:25
Thank you so much for all the help. I ended up downgrading to the previous version of Ai 24.3 and it's working again. Will wait for the updates before trying to upgrade again.

**Comment by grimabe** [comment] 2020-11-16 22:17
Hi, I am having the same issue : 

I am under macOS Big Sur (11.0.1)
It crashes under Illustrator 25.064 :
- on import variables button clicked after opening a document
- even if we don't open any document and just try to create the XML.

But it is working under 24.2.

I tried to Debug the script under 25.064 with the (Adobe ExtendScript Toolkit in VSCode) debugger enabled.
Unfortunately, Illustrator freezes after selecting the csv file to import, so I don't know which instructions causes the crash.
Let me know If I can help in any way.

**Comment by Silly-V** [comment] 2020-11-16 22:59
I would like to find out which script line is the culprit. However, I need a new Mac to really test it, so I'm hoping that Adobe somehow fixes it and it disappears automatically. I'll try some more tests on my friend's Mac, but it did work the last time - which makes this issue even harder to comprehend. Another person did a test as well and was able to reproduce the error first-time.

**Comment by Silly-V** [comment] 2020-11-17 14:19
The Illustrator User-Voice bug-submission site is here if anyone would like to upvote an Adobe bug-fix for this.
https://illustrator.uservoice.com/forums/601447-illustrator-desktop-bugs/suggestions/41739235-illustrator-2021-version-25-0-0-crashing-when-ru

**Comment by Silly-V** [comment] 2021-01-07 15:13
Good news, Adobe has addressed and fixed the bug in version 25.1!

**Closed by Silly-V** 2021-01-07 15:13 UTC
