### ISSUE TITLE
Adobe Illustrator - Not Responding

### ISSUE THREAD

**Issue by tridentgrafix** [Silly-V/Adobe-Illustrator#13] opened 2017-12-07 22:49 UTC
Hi,

I am using this on CC 21.0.2, it crashes the moment I press the 'Import Variables' button and Adobe stops responding.

It works when I delete all the images from the artboards, is there a restriction in terms of image sizes that causes this to crash?

Many thanks

**Comment by Silly-V** [comment] 2017-12-07 23:02
It depends, there's a lot to be discovered by all various users performing all kinds of tests. For example, there was a user who had a problem with image importing. After I took a look at his file, I saw that one PNG file was in some way corrupted and causing an error. It was causing the error when also being placed in manually or when I tried to open it in Photoshop. So we narrowed the cause down to a corrupted image file. However, it was simply an error alert as opposed to a full-on crash.
Your case is different and sounds like it could be the amount of images or sizes.
Try to create a manual test whereby you place all the same images at the same time into the document.
Also I'd like to test your file, if you can send it over to vasily.hall@gmail.com

**Comment by tridentgrafix** [comment] 2017-12-11 01:26
Hi

Thank you for your informative response. 

I will certainly send over the AI file.

I was wondering if I should instead save background images on a separate AI file and then link them via the CSV as image links. 

Does your tool allow image files to be AI format?

**Comment by Silly-V** [comment] 2017-12-11 14:45
Yes, .ai files are supported, as well as any file which can be placed into an Illustrator document as a linked file.

**Comment by Silly-V** [comment] 2017-12-15 16:57
Can you please send the .ai file? With no file set to experiment, this issue will be closed in an arbitrary amount of days.

**Comment by Silly-V** [comment] 2017-12-28 07:43
Since (at the time of this) this has not come up yet, perhaps the issue is related to Illustrator's native ability to successfully render a certain amount of placed items, or it could be related to some content of those placed items which do not play well with the execution including all the various factors at play. Can do a test when a sample file is sent over.

**Closed by Silly-V** 2017-12-28 07:43 UTC
