### ISSUE TITLE
Illustrator Stops responding after selecting CSV file

### ISSUE THREAD

**Issue by alexstojda** [Silly-V/Adobe-Illustrator#17] opened 2018-03-16 17:19 UTC
After selecting the Choose CSV file, the script and Illustrator freezes and stops responding.

**Comment by Silly-V** [comment] 2018-03-16 17:27
I hope they didn't add something with the new update to disfavor the VI script and to favor their own new csv import instead.
What system and version are you running ? Was it always like this or is this your first time to run the VI script ?

**Comment by alexstojda** [comment] 2018-03-16 17:36
Ran it last week and it worked perfectly!
________________________________

**Comment by alexstojda** [comment] 2018-03-16 17:39
Illustrator Version: 22.0.1 (64-bit)
OS: Windows 10, version 1709

**Comment by Silly-V** [comment] 2018-03-16 18:01
How long have you been using it? Is it only since the new update that this issue comes up?
Also can you send your files to me at Vasily.hall@gmail.com ?

**Comment by Silly-V** [comment] 2018-03-19 14:14
Hi, do you have something I can examine?

**Comment by Silly-V** [comment] 2018-03-22 20:00
I asked someone else to test on their Windows 10, appears to work OK.
... without your files I can't really help you - so if it goes for a few months, I'll close this unresolved issue.

**Comment by Silly-V** [comment] 2018-04-06 20:42
User reported in PM that error was caused by stray data cell in a line after 6000. With edited data, the script appeared to work properly.

**Closed by Silly-V** 2018-04-06 20:42 UTC
